0:
  Name: ABORT
  Address: EXIT
  State: EXIT
  GSTIN No: EXIT

1:  
  Name: ABHAY SOLVENTS PVT.LTD.  
  Address: KOPPAL  
  State: KARNATAKA  
  GSTIN No: 29AACCA1284D1ZY  

2:  
  Name: ASHWINI AGROTECH,PVT.LTD.  
  Address: YEDLAPALLY,TENALI,GUNTUR.  
  State: ANDHRA PRADESH  
  GSTIN No: 37AADCA7063K1ZG  

3:  
  Name: BAHETI EXTRACTIONS  
  Address: Sy. No. 69 & 70, Nandaram Village, Balanagar Mandal, Mahbubnagar Dist  
  State: TELANGANA  
  GST NO: 36AAUFB8757B1Z2  

4:  
  Name: CHERUKUPALLY AGRO PRODUCTS PVT LTD.  
  Address: KODUR VILLAGE , MAHABUBNAGAR  
  State: TELANGANA  
  GSTIN No: 36AADCC5234G1ZW  

5:  
  Name: MADHAVI EDIBLE BRAN OILS PVT LTD  
  Address: BEHIND THAYAMMA TEMPLE, RAICHUR  
  State: KARNATAKA  
  GSTIN No: 29AAGCM8969D1ZW  

6:  
  Name: MAHESH FATS & OILS LTD
  Address: Kattedan  
  State: Telangana  
  GSTIN No: 36AABCM5501E1ZY  

7:  
  Name: MAHESHWARI OIL INDUSTRIES PVT LTD  
  Address: MAILADEVAPALLY vil , CHANDRAYANGUTTA , R.R.Dist  
  State: TELANGANA  
  GSTIN No: 36AAACM9466H1Z5  

8:  
  Name: NICO AGRO OIL PRODUCTS PVT LTD  
  Address: PERECHERLA , GUNTUR  
  State: Andhra Pradesh  
  GSTID No: 37AABCN2684F1ZF  

9:  
  Name: RAICHUR SOLVENTS LIMITED  
  Address: Plot 57, 58 Industrial Area, Raichur  
  State: Karnataka  
  GSTIN No: 29AAACR7310R1ZV  

10:  
  Name: ROHIT EXTRACTIONS PRIVATE LIMITED  
  Address: Narapally , Hyderabad  
  State: Telangana  
  GSTIN No: 36AABCR0726J1ZH  

11:  
  Name: SHYAM SOLVEX INDIA PRIVATE LIMITED  
  Address: Shadnagar  
  State: Telangana  
  GSTIN No: 36AAJCS5049P1ZM  
  Mail: shyam  

12:  
  Name: SKM ANIMAL FEEDS AND FOODS (INDIA) PRIVATE LIMITED  
  Address: NANAJAIUTHUKULI POST, MODAKKURICHI TK  
  State: TAMILNADU  
  GSTIN No: 33AACCS9493E1Z6  

13:  
  Name: SMS9 AGRO OILS LLP  
  Address: yadagiripally , Miryalaguda , Nalgonda dist  
  State: Telangana  
  GSTIN No: 36ACZFS7463G1Z9  
  Mail: sms9agrooils@gmail.com  
  Mobile: 91779 45390  

14:  
  Name: SULOCHANA AGRO & INFRATECH PRIVATE LIMITED  
  Address: SY 7 , PALWAI VILLAGE , GURRAMPODE MANDAL , NALGONDA DIST  
  State: TELANGANA  
  GSTIN No: 36AAKCS6435J1ZX  

15:  
  Name: VASAVI SOLVENTS  
  Address: KUKKADAM village, MADGULAPALLY mandal, MIRYALAGUDA , NALGONDA dist  
  State: TELANGANA  
  GSTIN No: 36AATFV4888J1Z2  
  Mail: Email.vasavisolvents21@gmail.com  
  Mobile: +91 8341302113  