0:
  Name: ABORT
  Address: EXIT
  State: EXIT
  GSTIN No: EXIT

1:
  Name: Mahesh Fats & Oils Limited.
  Address: Kattedan
  State: Telangana
  GSTIN No: 36AABCM5501E1ZY

2:
  Name: CHERUKUPALLY AGRO PRODUCTS PVT LTD.
  Address: KODUR VILLAGE , MAHABUBNAGAR
  State: TELANGANA
  GSTIN No: 36AADCC5234G1ZW

3:
  Name: BAHETI EXTRACTIONS
  Address: Sy. No. 69 & 70, Nandaram Village, Balanagar Mandal, Mahbubnagar Dist. - 509202.
  State: TELANGANA
  GST NO: 36AAUFB8757B1Z2

4:
  Name: SHYAM SOLVEX INDIA PRIVATE LIMITED
  Address: Shadnagar
  State: Telangana
  GSTIN No: 36AAJCS5049P1ZM

5:
  Name: MAHESHWARI OIL INDUSTRIES PVT LTD
  Address: MAILADEVAPALLY vil , CHANDRAYANGUTTA , R.R.Dist
  State: TELANGANA
  GSTIN No: 36AAACM9466H1Z5

6:
  Name: NICO AGRO OIL PRODUCTS PVT LTD
  Address: PERECHERLA , GUNTUR
  State: Andhra Pradesh
  GSTID No: 37AABCN2684F1ZF

7:
  Name: ABHAY SOLVENTS PVT.LTD.
  Address: KOPPAL
  State: KARNATAKA
  GSTIN No: 29AACCA1284D1ZY

8:
  Name: MADHAVI EDIBLE BRAN OILS PVT LTD
  Address: BEHIND THAYAMMA TEMPLE, RAICHUR
  State: KARNATAKA
  GSTIN No: 29AAGCM8969D1ZW

9:
  Name: RAICHUR SOLVENTS LIMITED
  Address: Plot 57, 58 Industrial Area, Raichur
  State: Karnataka
  GSTIN No: 29AAACR7310R1ZV

10:
  Name: SKM ANIMAL FEEDS AND FOODS (INDIA) PRIVATE LIMITED
  Address: NANAJAIUTHUKULI POST, MODAKKURICHI TK,TAMILNADU-638104
  State: TAMILNADU
  GSTIN No: 33AACCS9493E1Z6

11:
  Name : ROHIT EXTRACTIONS PRIVATE LIMITED
  Address : Narapally , Hyderabad
  State : Telangana
  GSTIN No : 36AABCR0726J1ZH

